// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telelingo.DataContext;

#nullable disable

namespace Telelingo.DataContext.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240528200326_UpdateWordEntity")]
    partial class UpdateWordEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Telelingo.EntityModels.Chat", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("Telelingo.EntityModels.ChatWord", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ShowOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "WordId");

                    b.HasIndex("WordId");

                    b.ToTable("ChatWord");
                });

            modelBuilder.Entity("Telelingo.EntityModels.Word", b =>
                {
                    b.Property<long>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WordId");

                    b.ToTable("Word");
                });

            modelBuilder.Entity("Telelingo.EntityModels.ChatWord", b =>
                {
                    b.HasOne("Telelingo.EntityModels.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Telelingo.EntityModels.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
